### PR TITLE
migrate to hardhat

### PR DESCRIPTION
**Pull request by thegostep**

### CODE REVIEW

**Comment by ahnaguib** [comment]
Is it possible to make the renames get detected as rename to see SxS diffs?

**Comment by thegostep** [comment]
> Is it possible to make the renames get detected as rename to see SxS diffs?

You can see the line by line diff in this commit: https://github.com/ampleforth/uFragments/pull/164/commits/f8530d47d4511bb5230199c34b1434cdc35d5cec

**Comment by ahnaguib** [comment]
> > Is it possible to make the renames get detected as rename to see SxS diffs?
> 
> @ahnaguib You can see the line by line diff in this commit: [f8530d4](https://github.com/ampleforth/uFragments/commit/f8530d47d4511bb5230199c34b1434cdc35d5cec)

Thanks!

**Review by nithinkrishna — APPROVED** [review]

**Review by brandoniles — APPROVED** [review]
LGTM!

**Pull request merged**
